- title: 'Beginner Tipsy Cab Driver'
  score: 0
- title: 'Beginner Tipsy Cab Driver'
  score: 0
- title: 'Flappy Cab Driver'
  score: 100
- title: 'Angry Cab Driver'
  score: 200
- title: 'Über-Angry Cab Driver'
  score: 300
- title: 'Über-Angry Flappy Union Member'
  score: 400
- title: 'Über-Furious Union Member Ninjya'
  score: 500
- title: 'Serious Über-smasher Nerdy Ninjya'
  score: 600
- title: 'Über-Dark-Weider of Cab Drivers'
  score: 1000