- title: 'Beginner Tipsy Cab Driver'
  score: 0
- title: 'Angry Cab Driver'
  score: 100
- title: 'Pissed-Off Cab Driver'
  score: 200
- title: 'Über-Angry Cab Driver'
  score: 300
- title: 'Über-Angry Taxi Union Member'
  score: 400
- title: 'Über-Furious Supreme Union Leader'
  score: 500
- title: 'Aspiring Travis Bickle'
  score: 600
- title: 'Deranged Taxi Medallion Hoarder'
  score: 700
- title: 'Traffic-Stopping Taxi Lunatic'
  score: 800
- title: 'Disruptor of Digital Disruptors'
  score: 900
- title: 'Das Übermensch'
  score: 1000